sonar.projectKey=mohammadaziz-dev_SmartCommerce_Angular
sonar.organization=mohammadaziz-dev

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.javascript.lcov.reportPaths=frontend/angular-app/coverage/lcov.info
