sonar.projectKey=mohammadaziz-dev_SmartCommerce_React
sonar.organization=mohammadaziz-dev

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info